Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -32,10 +32,19 @@ jobs:
           python3 -m pip install markdown
       - name: Check for tags
         run: |
-          # COMMENT OUT THE FOLLOWING LINE IF YOU DON'T WANT TO CHECK ALL FILES
-          # FILES=$(git diff --name-only -r HEAD^1 HEAD)
+          FILES=$(git diff --name-only ${{ github.event.after }} ${{ github.event.before }})
 
-          # GRAB ONLY THE FILES THAT END IN .md IN THE ENTIRE REPO, REMOVE all non characters
+          for FILE in $FILES; do
+            if [[ $FILE == *.md ]]; then
+              echo "Checking tags in $FILE"
+              ERROR=$(python3 check-tags.py <<< $FILE)
+              if [ '$ERROR' == 1 ]; then
+                echo "Error in $FILE: $ERROR"
+                exit 1
+              fi
+            fi
+          done
+
           FILES=$(git ls-files | grep .md | sed 's/[^a-zA-Z0-9\/\._-]/ /g')
           echo $FILES
 
@@ -43,7 +52,7 @@ jobs:
             if [[ $FILE == *.md ]]; then
               echo "Checking tags in $FILE"
               ERROR=$(python3 check-tags.py <<< $FILE)
-              if [ "$ERROR" == 1 ]; then
+              if [ '$ERROR' == 1 ]; then
                 echo "Error in $FILE: $ERROR"
                 exit 1
               fi
