Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -38,6 +38,10 @@ jobs:
           for FILE in $FILES; do
             if [[ $FILE == *.md ]]; then
               echo "Checking tags in $FILE"
-              python3 check-tags.py <<< $FILE
+              ERROR <<< $(python3 check-tags.py <<< $FILE)
+              if [ '$ERROR' == 1 ]; then
+                echo "Error in $FILE: $ERROR"
+                exit 1
+              fi
             fi
           done
