Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -38,6 +38,9 @@ jobs:
           for FILE in $FILES; do
             if [[ $FILE == *.md ]]; then
               echo "Checking tags in $FILE"
-              echo $(python3 check-tags.py <<< $FILE)
+              if [ -n $(python3 check-tags.py <<< $FILE) ]; then
+                echo "Error in $FILE: $ERROR"
+                exit 1
+              fi
             fi
           done
